name: example
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_exporter:
    path: ../
  freezed_annotation: ^0.14.3

dev_dependencies:
  build_runner: ^2.1.2
  pedantic: ^1.10.0
