name: example_package
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.14.3
  auto_exporter_annotation:
    path: ../auto_exporter_annotation

dev_dependencies:
  build_runner: ^2.1.2
  pedantic: ^1.10.0
  auto_exporter:
    path: ../
