name: auto_exporter
description: A new Flutter package that allows you to auto export types globally.
version: 1.2.1
homepage: https://github.com/normidar/auto_exporter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^3.0.0
  source_gen: ^1.2.1
  build: ^2.2.1
  build_resolvers: ^2.0.6
  meta: ^1.7.0
  glob: ^2.0.2

dev_dependencies:
  effective_dart: ^1.3.2
  pedantic: ^1.11.1
