name: auto_exporter
description: A Dart package that allows you to auto export files, see README.md to know how to use it, just use the terminal and change the dart file name.
version: 1.4.2
homepage: https://github.com/normidar/auto_exporter
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.0
  build_resolvers: ^2.0.4
  source_gen:
  glob: ^2.0.0
  auto_exporter_annotation:
    path: auto_exporter_annotation

dev_dependencies:
  effective_dart: ^1.3.2
  lints: ^1.0.1 # 2.0.0 is in devlop
